/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package gui;

import javax.swing.JOptionPane;
import modelo.OLT;
import persistencia.GestorPersistencia;

/**
 *
 * @author USER
 */
public class VentanaInicialOLT extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaInicialOLT.class.getName());

    /**
     * Creates new form VentanaInicialOLT
     * @param parent
     */
    public VentanaInicialOLT(java.awt.Frame parent) {
        //super(parent, modal);
        super(parent, "Configuracion de OLT", true);    
        initComponents();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Ltitulo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        BCrear = new javax.swing.JButton();
        Bcargar = new javax.swing.JButton();
        Tid = new javax.swing.JTextField();
        Tnombre = new javax.swing.JTextField();
        Tbajada = new javax.swing.JTextField();
        Tsubida = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        Ltitulo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Ltitulo.setText("Sistema de Gestion GPON");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("ID de OLT:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Nombre:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Capacidad de Bajada (Mbps):");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Capacidad de Subida (Mbps):");

        BCrear.setBackground(new java.awt.Color(51, 255, 0));
        BCrear.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BCrear.setText("Crear Nueva OLT");
        BCrear.addActionListener(this::BCrearActionPerformed);

        Bcargar.setBackground(new java.awt.Color(0, 0, 255));
        Bcargar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Bcargar.setForeground(new java.awt.Color(255, 255, 255));
        Bcargar.setText("Cargar OLT existente");
        Bcargar.addActionListener(this::BcargarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addComponent(Ltitulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Tid, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Tnombre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Tbajada, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Tsubida, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BCrear)
                            .addComponent(Bcargar))))
                .addGap(43, 43, 43))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Ltitulo)
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Tid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Tnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Tbajada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(Tsubida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(BCrear)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Bcargar)
                .addGap(45, 45, 45))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BCrearActionPerformed
        // TODO add your handling code here:
        String id = null, nombre=null;
        double bajada=0, subida=0;
        try{
            id=Tid.getText();
            if(id.isBlank()){
                throw new IllegalArgumentException("Ingrese una ID");
            }
        }catch(IllegalArgumentException e){
            JOptionPane.showMessageDialog(this, e.getLocalizedMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            Tid.selectAll();
            Tid.requestFocus();
            return;
        }
        
        try{
            nombre = Tnombre.getText();
            if(nombre.isBlank()){
                throw new IllegalArgumentException("Ingrese un Nombre");
            }
        }catch(IllegalArgumentException e){
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            Tnombre.selectAll();
            Tnombre.requestFocus();
            return;
        } 
        
        try{
            bajada = Double.parseDouble(Tbajada.getText());
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this,"Ingrese una capacidad de bajada valida", "Error", JOptionPane.ERROR_MESSAGE);
            Tbajada.selectAll();
            Tbajada.requestFocus();
            return;
        }
        
        try{
            subida = Double.parseDouble(Tsubida.getText());
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this,"Ingrese una capacidad de subida valida", "Error", JOptionPane.ERROR_MESSAGE);
            Tsubida.selectAll();
            Tsubida.requestFocus();
            return;
        }
        
        oltseleccionada = new OLT(bajada, subida, id, nombre, 0);
        JOptionPane.showMessageDialog(this, "OLT creada: " +oltseleccionada.getId(), "Exito", JOptionPane.INFORMATION_MESSAGE);
        dispose(); 
    }//GEN-LAST:event_BCrearActionPerformed

    private void BcargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BcargarActionPerformed
        // TODO add your handling code here:
        OLT oltcargada = gestor.cargar();
        
        if(oltcargada == null){
            JOptionPane.showMessageDialog(this,"No se encontro ninguna OLT guardada. Debe de crear una nueva", "Error", JOptionPane.ERROR_MESSAGE);
            BCrear.requestFocus();
        }
        else {
            oltseleccionada = oltcargada;
            JOptionPane.showMessageDialog(this, "OLT cargada: " +oltcargada.getId(), "Exito", JOptionPane.INFORMATION_MESSAGE);
            dispose();
        }
        
    }//GEN-LAST:event_BcargarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                VentanaInicialOLT dialog = new VentanaInicialOLT(new javax.swing.JFrame());
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BCrear;
    private javax.swing.JButton Bcargar;
    private javax.swing.JLabel Ltitulo;
    private javax.swing.JTextField Tbajada;
    private javax.swing.JTextField Tid;
    private javax.swing.JTextField Tnombre;
    private javax.swing.JTextField Tsubida;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
    private OLT oltseleccionada;
    private GestorPersistencia gestor;
    
    public OLT getOLTseleccionada(){
        return oltseleccionada;
    }
}
