/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import java.io.IOException;
import java.text.ParseException;
import javax.swing.*;
import modelo.OLT;
import modelo.ONT;
import modelo.ONTEmpresarial;
import modelo.ONTResidencial;
import persistencia.GestorPersistencia;

/**
 *
 * @author USER
 */
public class VentanaPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName());
    private ButtonModel m;

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal(OLT olt) {
        this.olt = olt;
        this.gestor = new GestorPersistencia("red_gpon.dat");
        
        initComponents();
    setTitle("Sistema GPON - " + olt.getId());
    setSize(600, 400);
    setLocationRelativeTo(null);
    setDefaultCloseOperation(EXIT_ON_CLOSE);
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        Ltitulo = new javax.swing.JLabel();
        Lid = new javax.swing.JLabel();
        Tid = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        Tnombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Tdistancia = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Lextra = new javax.swing.JLabel();
        Tbanda = new javax.swing.JTextField();
        Bagregar = new javax.swing.JButton();
        Beliminar = new javax.swing.JButton();
        Bguardar = new javax.swing.JButton();
        RBempresarial = new javax.swing.JRadioButton();
        RBresidencial = new javax.swing.JRadioButton();
        Lnumerico = new javax.swing.JLabel();
        Spinner = new javax.swing.JSpinner();
        Ltv = new javax.swing.JLabel();
        Ctv = new javax.swing.JCheckBox();
        BverRed = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(600, 430));

        Ltitulo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Ltitulo.setText("Sistema de Gestion GPON OLT - ONT");

        Lid.setText("ID dispositivo");

        Tid.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Tid.addActionListener(this::TidActionPerformed);

        jLabel1.setText("Nombre");

        Tnombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Tnombre.addActionListener(this::TnombreActionPerformed);

        jLabel2.setText("Distancia de Fibra (km)");

        Tdistancia.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Tdistancia.addActionListener(this::TdistanciaActionPerformed);

        jLabel3.setText("Perfil");

        Lextra.setText("Banda");

        Tbanda.addActionListener(this::TbandaActionPerformed);

        Bagregar.setBackground(new java.awt.Color(204, 255, 51));
        Bagregar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Bagregar.setText("+Agregar");
        Bagregar.addActionListener(this::BagregarActionPerformed);

        Beliminar.setBackground(new java.awt.Color(255, 51, 51));
        Beliminar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Beliminar.setText("-Eliminar");
        Beliminar.addActionListener(this::BeliminarActionPerformed);

        Bguardar.setBackground(new java.awt.Color(51, 51, 255));
        Bguardar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Bguardar.setForeground(new java.awt.Color(255, 255, 255));
        Bguardar.setText("Guardar");
        Bguardar.addActionListener(this::BguardarActionPerformed);

        buttonGroup1.add(RBempresarial);
        RBempresarial.setText("Empresarial");
        RBempresarial.addActionListener(this::RBempresarialActionPerformed);

        buttonGroup1.add(RBresidencial);
        RBresidencial.setText("Residencial");
        RBresidencial.addActionListener(this::RBresidencialActionPerformed);

        Lnumerico.setText("Cantidad de Usuarios");

        Spinner.setModel(new javax.swing.SpinnerNumberModel());

        Ltv.setText("Tiene TV?");

        Ctv.setText("SI");

        BverRed.setBackground(new java.awt.Color(0, 153, 0));
        BverRed.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BverRed.setForeground(new java.awt.Color(255, 255, 255));
        BverRed.setText("Ver Red ");
        BverRed.addActionListener(this::BverRedActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Bagregar)
                        .addGap(9, 9, 9)
                        .addComponent(Bguardar, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(BverRed)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Beliminar))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(RBempresarial)
                        .addGap(6, 6, 6)
                        .addComponent(RBresidencial))
                    .addComponent(Lid)
                    .addComponent(Tid)
                    .addComponent(jLabel1)
                    .addComponent(Tnombre)
                    .addComponent(jLabel2)
                    .addComponent(Tdistancia, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Tbanda, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(Spinner)
                        .addGap(12, 12, 12)
                        .addComponent(Ctv, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Lextra)
                        .addGap(57, 57, 57)
                        .addComponent(Lnumerico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(12, 12, 12)
                        .addComponent(Ltv)))
                .addContainerGap(52, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(Ltitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Ltitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Lid)
                .addGap(17, 17, 17)
                .addComponent(Tid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Tnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jLabel2)
                .addGap(12, 12, 12)
                .addComponent(Tdistancia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RBempresarial)
                    .addComponent(RBresidencial))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lextra)
                    .addComponent(Lnumerico)
                    .addComponent(Ltv))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Tbanda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Spinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Ctv))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Bagregar)
                    .addComponent(Beliminar)
                    .addComponent(Bguardar)
                    .addComponent(BverRed))
                .addGap(37, 37, 37))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TidActionPerformed

    private void TnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TnombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TnombreActionPerformed

    private void TdistanciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TdistanciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TdistanciaActionPerformed

    private void TbandaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TbandaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TbandaActionPerformed

    private void BagregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BagregarActionPerformed
        double km=0, banda = 0 ;
        String nombre= null, id=null;
        int cant = 0;
        boolean tv = false;
        
        try{
            id = Tid.getText();
            if(id.isBlank()){
                throw new IllegalArgumentException("Ingrese una id");
            }
        }catch(IllegalArgumentException e){
            JOptionPane.showMessageDialog(this, e.getLocalizedMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            Tid.selectAll();
            Tid.requestFocus();
            return;
        }
        
        try{
            nombre = Tnombre.getText();
            if(nombre.isBlank()){
                throw new IllegalArgumentException("Ingrese un nombre");
            }
        }catch(IllegalArgumentException e){
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            Tnombre.selectAll();
            Tnombre.requestFocus();
            return;
        } 
    
        try{
            km = Double.parseDouble(Tdistancia.getText());
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this,"Ingrese una distancia valida", "Error", JOptionPane.ERROR_MESSAGE);
            Tdistancia.selectAll();
            Tdistancia.requestFocus();
            return;
        }
        try{
        if(buttonGroup1.isSelected(m)){
           throw new IllegalArgumentException("Seleccione una opcion"); 
        } 
        }catch(IllegalArgumentException e){
                JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                RBresidencial.requestFocus();
                return;
                }
       
        
        try{
            banda=Double.parseDouble(Tbanda.getText());
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this,"Ingrese una cantidad de MB valida", "Error", JOptionPane.ERROR_MESSAGE);
            Tbanda.selectAll();
            Tbanda.requestFocus();
            return;
        }
        
        try {
            Spinner.commitEdit();
        } catch (ParseException ex) {
            System.getLogger(VentanaPrincipal.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
            Spinner.requestFocus();
            return;
        }
        cant = (int) Spinner.getValue();
        
        if(RBresidencial.isSelected()){
            tv = Ctv.isSelected();
            ONT ont = new ONTResidencial(cant, tv, id, nombre, km);
            ont.setAnchoBajada(banda);
            try{
                olt.agregarONT(ont);
            }catch(IllegalArgumentException e){
             JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
             return;
            }
            JOptionPane.showMessageDialog(this, "ONT agregada: " +ont.getId(), "Exito", JOptionPane.INFORMATION_MESSAGE);   
        }
        else if(RBempresarial.isSelected()){
            ONT ont = new ONTEmpresarial(banda, cant, id, nombre, km);
            try{
                olt.agregarONT(ont);
            }catch(IllegalArgumentException e){
             JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
             return;
            }
            JOptionPane.showMessageDialog(this, "ONT agregada: " +ont.getId(), "Exito", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_BagregarActionPerformed

    private void RBempresarialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBempresarialActionPerformed
        Lextra.setText("SLA Garantizado");
        Lnumerico.setText("IP's fijas");
        Ctv.setEnabled(false);    
    }//GEN-LAST:event_RBempresarialActionPerformed

    private void RBresidencialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBresidencialActionPerformed
        Lextra.setText("MB contratado");
        Lnumerico.setText("Cantidad de Usuarios");
        Ctv.setEnabled(true);
    }//GEN-LAST:event_RBresidencialActionPerformed

    private void BeliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BeliminarActionPerformed
        // TODO add your handling code here:
        double km=0, banda = 0 ;
        String nombre= null, id=null;
        int cant = 0;
        boolean tv = false;
        
        try{
            id = Tid.getText();
            if(id.isBlank()){
                throw new IllegalArgumentException("Ingrese una id");
            }
        }catch(IllegalArgumentException e){
            JOptionPane.showMessageDialog(this, e.getLocalizedMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            Tid.selectAll();
            Tid.requestFocus();
            return;
        }
        
        try{
            nombre = Tnombre.getText();
            if(nombre.isBlank()){
                throw new IllegalArgumentException("Ingrese un nombre");
            }
        }catch(IllegalArgumentException e){
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            Tnombre.selectAll();
            Tnombre.requestFocus();
            return;
        } 
    
        try{
            km = Double.parseDouble(Tdistancia.getText());
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this,"Ingrese una distancia valida", "Error", JOptionPane.ERROR_MESSAGE);
            Tdistancia.selectAll();
            Tdistancia.requestFocus();
            return;
        }
        try{
        if(buttonGroup1.isSelected(m)){
           throw new IllegalArgumentException("Seleccione una opcion"); 
        } 
        }catch(IllegalArgumentException e){
                JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                RBresidencial.requestFocus();
                return;
                }
       
        
        try{
            banda=Double.parseDouble(Tbanda.getText());
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this,"Ingrese una cantidad de MB valida", "Error", JOptionPane.ERROR_MESSAGE);
            Tbanda.selectAll();
            Tbanda.requestFocus();
            return;
        }
        
        try {
            Spinner.commitEdit();
        } catch (ParseException ex) {
            System.getLogger(VentanaPrincipal.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
            Spinner.requestFocus();
            return;
        }
        cant = (int) Spinner.getValue();
        if(RBempresarial.isSelected()){
            ONT ont = new ONTEmpresarial(banda, cant, id, nombre, km);
            try{
                olt.eliminarONT(ont);
            }catch(IllegalArgumentException e){
               JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
               return; 
            }
            JOptionPane.showMessageDialog(this, "ONT eliminada: " +ont.getId(), "Exito", JOptionPane.INFORMATION_MESSAGE);
        }
        else if(RBresidencial.isSelected()){
            tv=Ctv.isSelected();
            ONT ont = new ONTResidencial(cant, tv, id, nombre, km);
            try{
                olt.eliminarONT(ont);
            }catch(IllegalArgumentException e){
               JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
               return; 
            }
            JOptionPane.showMessageDialog(this, "ONT eliminada: " +ont.getId(), "Exito", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_BeliminarActionPerformed

    private void BguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BguardarActionPerformed
        // TODO add your handling code here:
            try{
                gestor.guardar(olt);
                JOptionPane.showMessageDialog(this, "OLT: " + olt.getId() + " guardado con exito.", "Exito", JOptionPane.INFORMATION_MESSAGE);
            }catch(IOException e){
                JOptionPane.showMessageDialog(this, e.getLocalizedMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
            
    }//GEN-LAST:event_BguardarActionPerformed

    private void BverRedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BverRedActionPerformed
        // TODO add your handling code here:
        dialogRed = new DialogRed(this, olt);
        dialogRed.setVisible(true);
        timerActualizacion = new Timer(1000,e -> {
            dialogRed.actualizarRed(olt);
        });
        timerActualizacion.start();
    }//GEN-LAST:event_BverRedActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bagregar;
    private javax.swing.JButton Beliminar;
    private javax.swing.JButton Bguardar;
    private javax.swing.JButton BverRed;
    private javax.swing.JCheckBox Ctv;
    private javax.swing.JLabel Lextra;
    private javax.swing.JLabel Lid;
    private javax.swing.JLabel Lnumerico;
    private javax.swing.JLabel Ltitulo;
    private javax.swing.JLabel Ltv;
    private javax.swing.JRadioButton RBempresarial;
    private javax.swing.JRadioButton RBresidencial;
    private javax.swing.JSpinner Spinner;
    private javax.swing.JTextField Tbanda;
    private javax.swing.JTextField Tdistancia;
    private javax.swing.JTextField Tid;
    private javax.swing.JTextField Tnombre;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
    
    
    private OLT olt;
    private GestorPersistencia gestor;
    private PanelRed panelRed;
    private Timer timerActualizacion;
    private DialogRed dialogRed;
}
